stages:
  - build
  - dev-deploy
  - prod-deploy

Docker Build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker info
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build -t "$CI_REGISTRY_IMAGE":"$CI_COMMIT_TAG" .
    - docker push "$CI_REGISTRY_IMAGE":"$CI_COMMIT_TAG"
  only:
    - /^v\d{1,9}\.\d{1,9}\.\d{1,9}-[d][e][v]$/
    - /^v\d{1,9}\.\d{1,9}\.\d{1,9}-[p][r][o][d]$/
  tags:
    - build

deploy-to-development:
  stage: dev-deploy
  image: alpine
  before_script:
    - apk add openssh-client sshpass
  script:
    - sshpass -p "$DEV_SSH_KEY" ssh -o StrictHostKeyChecking=no cicd@172.30.150.12 "docker ps"
    - sshpass -p "$DEV_SSH_KEY" ssh -o StrictHostKeyChecking=no cicd@172.30.150.12 "docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY "
    - sshpass -p "$DEV_SSH_KEY" ssh -o StrictHostKeyChecking=no cicd@172.30.150.12 "docker pull "$CI_REGISTRY_IMAGE":"$CI_COMMIT_TAG""
    - sshpass -p "$DEV_SSH_KEY" ssh -o StrictHostKeyChecking=no cicd@172.30.150.12 "BUILD_VERSION_VACCINE_WEBSITE=$CI_COMMIT_TAG docker-compose -f /opt/vaccine-website/docker-compose.yml up -d"
  only:
    - /^v\d{1,9}\.\d{1,9}\.\d{1,9}-[d][e][v]$/
  tags:
    - build

deploy-to-production:
  stage: prod-deploy
  image: alpine
  before_script:
    - apk add openssh-client sshpass
  script:
    - sshpass -p "$PROD_SSH_KEY" ssh -o StrictHostKeyChecking=no cicd@172.30.150.11 "docker ps"
    - sshpass -p "$PROD_SSH_KEY" ssh -o StrictHostKeyChecking=no cicd@172.30.150.11 "docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY "
    - sshpass -p "$PROD_SSH_KEY" ssh -o StrictHostKeyChecking=no cicd@172.30.150.11 "docker pull "$CI_REGISTRY_IMAGE":"$CI_COMMIT_TAG""
    - sshpass -p "$PROD_SSH_KEY" ssh -o StrictHostKeyChecking=no cicd@172.30.150.11 "BUILD_VERSION_VACCINE_WEBSITE=$CI_COMMIT_TAG docker-compose -f /opt/vaccine-website/docker-compose.yml up -d"
  only:
    - /^v\d{1,9}\.\d{1,9}\.\d{1,9}-[p][r][o][d]$/
  tags:
    - build